---
title: " "
output: 
  html_document:
    toc_float: true
  
---

---
title: "STA 610: Multilevel and Hierarchical Models"
description: "Variance component models with fixed and random effects. Multilevel and hierarchical models for longitudinal and/or clustered data. Focus on model fitting and interpretation. Maximum likelihood and Bayesian inference and computation. Prerequisite: STA 360/601/602 and R programming skills."
markup: "mmark"
---



#Welcome to STA610

### Class Meetings

<font color="#6CA0DC"><i class="fas fa-university fa-lg"></i></font> &nbsp; Old Chem 116

<font color="#6CA0DC"><i class="fas fa-calendar-alt fa-lg"></i></font> &nbsp; MWF 11:45 - 1:00 (usually Mondays will be labs)


### Teaching team and office hours 


Note: office hours may vary due to travel and other commitments. Revisions to office hours will be noted via e-mail and on my office door. 

| Team member | Office hours | Location |
| ----------  | -------------------------------------         | ---- |
| [Professor David Dunson](https://stat.duke.edu/people/amy-h-herring)  <a href="mailto:dunson@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | TBD | 218 Old Chemistry |
 [TA Shounak Chattapadhyay](https://stat.duke.edu/people/xu-chen)  <a href="mailto:shounak.chattopadhyay@duke.edu, " title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | TBD | Old Chemistry
 [TA Patrick LeBlanc](https://stat.duke.edu/people/isaac-lavine)  <a href="mailto:patrick.leblanc@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp; | TBD | Old Chemistry
 [TA Zhuoqun (Cathy) Wang ](https://stat.duke.edu/people/xu-chen)  <a href="mailto:zhuoqun.wang@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | TBD | Old Chemistry
                  


### Materials

You should have access to a laptop and bring it to every class, fully charged. Texts and readings will be assigned as needed. The instructor and TA's will support computation in R/RStudio. 

Helpful resource materials for the course include the following.

- Hoff, CSSS - Statistics 560 Lecture notes (Sakai)

- [Gelman and Hill, Data Analysis Using Regression and Multilevel/Hierarchical Models](https://www.amazon.com/Analysis-Regression-Multilevel-Hierarchical-Models/dp/052168689X)


### Topics and Important Dates

STA 410/610 contain a mixture of lecture, lab, and combination sessions at the usual class and lab times. Frequent mini-assessments will be provided in class and lab to check mastery and identify areas for additional focus.

Note: this schedule is approximate and is likely to be modified as the course progresses. Some lab sessions will be swapped with lectures due to instructor travel or course timing. Assignments are due at the beginning of class unless otherwise specified. 



|Date           |Topic                      |Deliverables     |
| ----------    | ---------------------------         | --------------- |
| August 29     | Welcome and Introductions        | ANOVA warm-up (in class)        |
| August 21     | One Way ANOVA: Scalar and Matrix Formulations    |   Getting to Know You Sheet              |
| September 2     |  MLE's, Contrasts, Coding Schemes, and Interaction      |    Scientific Writing: ANOVA Results (in class)     |
| September 5    |  Lab: Hands-on with ANOVA     |  Group Lab Reports      |
| September 7   | Random Effects ANOVA | Group Policies Document Due |
| September 9   | Random Effects ANOVA|  |
| September 12  | Bayesian Estimation | Assignment 1 Due  |
| September 14  | Lab: Gibbs Sampling  |    |
| September 16  |Bayesian Estimation |  |
| September 19  | Lab: Visualizing Estimates |    |
| September 21  | Random Effects ANCOVA | Second lab report due  |
| September 23  | Higher Level Multi-Level Models and Case Study 1 Introduction |   |
| September 26  | Lab: Gibbs Sampling | Assignment 2 Due  |
| September 28  | Exam Review |  |
| September 30  | Exam 1 (in class)  | Exam 1 (in class) |
| October 3  |  Lab: Group Work on Case Study 1        |   |
| October 5     | Linear Mixed Effects Models | Exam 1 Returned (my deliverable)  | 
| October 7     | Lab: Help, I'm Behind! Hands-on Analysis and Q&A | Midsemester Grades Due (my deliverable)  |
| October 10    | Fall break  |  |
| October 12    |  Diagnostics and Influence Measures |  |
| October 14    | Bayesian Linear Mixed Effects Model for Longitudinal Data |   |
| October 17    | Lab: Longitudinal Data |   |
| October 19    | Generalized Linear Mixed Effects Models | HW3 Released |
| October 21    | GLMM + 2 Case Study Presentations |  Case Study 1 Due, Group Lab Reports |
| October 24    | Lab |   | 
| October 26    | 4 Case Study Presentations |  |
| October 28    | 4 Case Study Presentations, GLM  | Reproducibility Evaluations Due  | 
| October 31    | Lab: Hierarchical Centering | Assignment 3 Due  | 
| November 2    | Crossed/Non-Nested Random Effects, Case Study 2 Introduction  |    |
| November 4    | Application: Election Prediction |  |
| November 7    | Lab: Who Votes? |   | 
| November 9    | Measurement Error |  |
| November 11    | Missing Data  |  |
| November 14   | Lab: Who Votes? |   |
| November 16   | Application: Meta Analysis | Group Lab Reports |
| November 18   | Multilevel Categorical Outcomes |  |
| November 21   | Assignment 4 Presentations | Assignment 4 Due (9am)  |
| November 23   | Thanksgiving break |
| November 25   | Thanksgiving break |
| November 28   | Lab: Exam Review |  | 
| November 30   | Assignment 4 Presentations |  |
| November 25   | Exam 2 (in class) | Exam 2 (in class) |
| December 2    | Make-Up Day (exam/assignment replacement opportunity) |  |


